### ISSUE TITLE
createsettingsfile ?

### ISSUE THREAD

**Issue by jpic** [adamchainz/django-settings-file#2]
We could add a command like `manage.py createsettings` that would build a config file that would inherit from the project's settings module.

It could prompt the user for variables, such as for DATABASES, CACHES ...

We could configure it with something like:

```
from yourproject import settings

DATABASES = {
  'default': {
    'NAME': {{ prompt('Database name', 'Name of the database to connect to') }}
  }
}
```

But then configuring Django deployments would become so easy I'd just call it sci-fi for now :D

That can be in a separate app of course, I'm not requesting an implementation here, but for your thoughts if you will as the developer of django-settings-file :P

**Comment by adamchainz** [comment]
Sounds to me like something more project-specific, e.g. most projects just use the same database name in test, stage, and prod. I can imagine a project providing such a thing, but I'm not sure there's much of a base that would be generally useful.

**Comment by jpic** [comment]
Of course, it is completely useless if you treat your servers and deployments as cattle when you're a professional.

I thought it could make it more comfortable for users who are just trying to make one deployment of one django project.
